const products = [
  {
    name: "عباية ياسمين الكلاسيكية",
    img: "/products/abaya5/1.png",
    price: 450,
    tag: "كلاسيك",
    url: "#",
    rating: 4.5,
    badge: "الأكثر مبيعاً",
  },
  {
    name: "عباية الأميرة المطرزة",
    img: "/products/abaya5/2.png",
    price: 580,
    tag: "فاخرة",
    url: "#",
    rating: 4.8,
    badge: "جديد",
  },
  {
    name: "عباية الشيفون الناعمة",
    img: "/products/abaya5/3.png",
    price: 420,
    tag: "عصرية",
    url: "#",
    rating: 4.3,
    badge: "",
  },
  {
    name: "عباية الدانتيل الملكية",
    img: "/products/abaya5/4.png",
    price: 650,
    tag: "راقية",
    url: "#",
    rating: 4.9,
    badge: "مميزة",
  },
  {
    name: "عباية الكريب البسيطة",
    img: "/products/abaya5/5.png",
    price: 380,
    tag: "يومية",
    url: "#",
    rating: 4.2,
    badge: "",
  },
  {
    name: "عباية اللؤلؤ المرصعة",
    img: "/products/abaya5/1.png",
    price: 720,
    tag: "مميزة",
    url: "#",
    rating: 4.7,
    badge: "فاخرة",
  },
  {
    name: "عباية الساتان الأنيقة",
    img: "/products/abaya5/2.png",
    price: 520,
    tag: "أنيقة",
    url: "#",
    rating: 4.6,
    badge: "جديد",
  },
  {
    name: "عباية الورود المطبوعة",
    img: "/products/abaya5/3.png",
    price: 480,
    tag: "جذابة",
    url: "#",
    rating: 4.4,
    badge: "",
  },
  {
    name: "عباية القطيفة الفاخرة",
    img: "/products/abaya5/4.png",
    price: 690,
    tag: "شتوية",
    url: "#",
    rating: 4.8,
    badge: "مميزة",
  },
  {
    name: "عباية الكريستال المتلألئة",
    img: "/products/abaya5/5.png",
    price: 850,
    tag: "استثنائية",
    url: "#",
    rating: 5.0,
    badge: "حصرية",
  },
];

console.log('Products loaded:', products.length);

export default products;
